---
# Scheduler jobs for the Open Delivery Gear extension
scheduler:
  jobs:
    # AWS orphan instances
    - name: "odg:task:report-orphan-vms-aws"
      spec: "@every 168h"
      desc: "Report orphan AWS EC2 Instances"
      queue: odg
      payload: |
        component_name: my-ocm-component
        component_version: v0.1.0
        query: |
          SELECT
            i.name,
            i.arch,
            i.instance_id,
            i.instance_type,
            i.state,
            i.subnet_id,
            i.vpc_id,
            i.platform,
            i.region_name,
            i.image_id,
            i.launch_time,
            i.account_id,
            i.vpc_name
          FROM aws_orphan_instance AS i
          WHERE
            housekeeper_ran_in_last('1 hour', 'aws:model:instance')

    # GCP orphan instances
    - name: "odg:task:report-orphan-vms-gcp"
      spec: "@every 168h"
      desc: "Report orphan GCP Virtual Machines"
      queue: odg
      payload: |
        component_name: my-ocm-component
        component_version: v0.1.0
        query: |
          SELECT
            i.name,
            i.hostname,
            i.instance_id,
            i.project_id,
            i.region,
            i.zone,
            i.cpu_platform,
            i.status,
            i.status_message,
            i.creation_timestamp,
            i.description,
            i.last_start_timestamp,
            i.last_stop_timestamp,
            i.last_suspend_timestamp,
            i.machine_type,
            i.gke_cluster_name,
            i.gke_pool_name
          FROM gcp_orphan_instance AS i
          WHERE
            housekeeper_ran_in_last('1 hour', 'gcp:model:instance')

    # Azure orphan virtual machines
    - name: "odg:task:report-orphan-vms-az"
      spec: "@every 168h"
      desc: "Report orphan Azure Virtual Machines"
      queue: odg
      payload: |
        component_name: my-ocm-component
        component_version: v0.1.0
        query: |
          SELECT
            vm.name,
            vm.subscription_id,
            vm.resource_group,
            vm.location,
            vm.provisioning_state,
            vm.vm_created_at,
            vm.hyper_v_gen,
            vm.vm_size,
            vm.power_state,
            vm.vm_agent_version
          FROM az_orphan_vm AS vm
          WHERE
            housekeeper_ran_in_last('1 hour', 'az:model:vm')

    #OpenStack orphan server
    - name: "odg:task:report-orphan-vms-openstack"
      spec: "@every 168h"
      desc: "Report orphan OpenStack Servers"
      queue: odg
      payload: |
        component_name: inventory
        component_version: v0.1.0
        query: |
          SELECT
            s.server_id,
            s.name,
            s.project_id,
            s.project_name,
            s.domain,
            s.region,
            s.user_id,
            s.availability_zone,
            s.status,
            s.image_id,
            s.server_created_at,
            s.server_updated_at
          FROM openstack_orphan_server AS s
          WHERE
            housekeeper_ran_in_last('1 hour', 'openstack:model:server')

    # GCP orphan Public IP Address
    - name: "odg:task:report-orphan-ip-addresses-gcp"
      spec: "@every 168h"
      desc: "Report orphan GCP Public Addresses"
      queue: odg
      payload: |
        component_name: my-ocm-component
        component_version: v0.1.0
        query: |
          SELECT
            a.rule_id,
            a.project_id,
            a.name,
            a.ip_address,
            a.ip_protocol,
            a.ip_version,
            a.all_ports,
            a.allow_global_access,
            a.backend_service,
            a.creation_timestamp,
            a.description,
            a.load_balancing_scheme,
            a.network,
            a.network_tier,
            a.port_range,
            a.region,
            a.service_label,
            a.service_name,
            a.subnetwork,
            a.target
          FROM gcp_orphan_public_address AS a
          WHERE
            housekeeper_ran_in_last('1 hour', 'gcp:model:forwarding_rule')
