name: Release
on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write

  publish-oci:
    uses: ./.github/workflows/oci-images.yaml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write
    needs:
      - test
    with:
      mode: release

  release-and-bump:
    uses: gardener/cc-utils/.github/workflows/release.yaml@v1
    permissions:
      contents: write
      packages: write
      id-token: write
    needs:
      - publish-oci
    with:
      release-commit-target: branch
      next-version: bump-patch
